<?php
	$tbl_item_transferencia_estoque = array(
			array( // row #0
				'id_transferencia' => 42,
				'id_produto' => 85254,
				'qtd_pedida' => 10,
				'qtd_transferida' => 15,
				'qtd_recebida' => 20,
				'id_deposito_entrada' => 56,
				'id_deposito_saida' => 14,
			),
			array( // row #1
				'id_transferencia' => 43,
				'id_produto' => 79577,
				'qtd_pedida' => 2,
				'qtd_transferida' => 1,
				'qtd_recebida' => 1,
				'id_deposito_entrada' => 53,
				'id_deposito_saida' => 44,
			),
			array( // row #2
				'id_transferencia' => 43,
				'id_produto' => 79582,
				'qtd_pedida' => 2,
				'qtd_transferida' => 1,
				'qtd_recebida' => 1,
				'id_deposito_entrada' => 53,
				'id_deposito_saida' => 44,
			),
			array( // row #3
				'id_transferencia' => 44,
				'id_produto' => 85495,
				'qtd_pedida' => 5,
				'qtd_transferida' => 1,
				'qtd_recebida' => 1,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #4
				'id_transferencia' => 45,
				'id_produto' => 85495,
				'qtd_pedida' => 2,
				'qtd_transferida' => 2,
				'qtd_recebida' => 2,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #5
				'id_transferencia' => 46,
				'id_produto' => 79577,
				'qtd_pedida' => 3,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #6
				'id_transferencia' => 46,
				'id_produto' => 79582,
				'qtd_pedida' => 4,
				'qtd_transferida' => 4,
				'qtd_recebida' => 4,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #7
				'id_transferencia' => 46,
				'id_produto' => 85495,
				'qtd_pedida' => 2,
				'qtd_transferida' => 2,
				'qtd_recebida' => 2,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #8
				'id_transferencia' => 47,
				'id_produto' => 79577,
				'qtd_pedida' => 2,
				'qtd_transferida' => 2,
				'qtd_recebida' => 2,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #9
				'id_transferencia' => 47,
				'id_produto' => 79582,
				'qtd_pedida' => 2,
				'qtd_transferida' => 2,
				'qtd_recebida' => 2,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #10
				'id_transferencia' => 47,
				'id_produto' => 85495,
				'qtd_pedida' => 2,
				'qtd_transferida' => 2,
				'qtd_recebida' => 2,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #11
				'id_transferencia' => 48,
				'id_produto' => 79577,
				'qtd_pedida' => 4,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #12
				'id_transferencia' => 48,
				'id_produto' => 79582,
				'qtd_pedida' => 4,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #13
				'id_transferencia' => 48,
				'id_produto' => 85495,
				'qtd_pedida' => 4,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #14
				'id_transferencia' => 49,
				'id_produto' => 79577,
				'qtd_pedida' => 5,
				'qtd_transferida' => 4,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #15
				'id_transferencia' => 49,
				'id_produto' => 79582,
				'qtd_pedida' => 5,
				'qtd_transferida' => 4,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #16
				'id_transferencia' => 49,
				'id_produto' => 85495,
				'qtd_pedida' => 5,
				'qtd_transferida' => 4,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #17
				'id_transferencia' => 50,
				'id_produto' => 79577,
				'qtd_pedida' => 10,
				'qtd_transferida' => 0,
				'qtd_recebida' => 0,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #18
				'id_transferencia' => 51,
				'id_produto' => 85138,
				'qtd_pedida' => 10,
				'qtd_transferida' => 10,
				'qtd_recebida' => 10,
				'id_deposito_entrada' => 59,
				'id_deposito_saida' => 6,
			),
			array( // row #19
				'id_transferencia' => 52,
				'id_produto' => 79577,
				'qtd_pedida' => 2,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #20
				'id_transferencia' => 52,
				'id_produto' => 79582,
				'qtd_pedida' => 2,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #21
				'id_transferencia' => 52,
				'id_produto' => 85495,
				'qtd_pedida' => 2,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #22
				'id_transferencia' => 53,
				'id_produto' => 79577,
				'qtd_pedida' => 2,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #23
				'id_transferencia' => 53,
				'id_produto' => 79582,
				'qtd_pedida' => 2,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #24
				'id_transferencia' => 53,
				'id_produto' => 85495,
				'qtd_pedida' => 1,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #25
				'id_transferencia' => 54,
				'id_produto' => 79577,
				'qtd_pedida' => 4,
				'qtd_transferida' => 4,
				'qtd_recebida' => 4,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #26
				'id_transferencia' => 54,
				'id_produto' => 79582,
				'qtd_pedida' => 2,
				'qtd_transferida' => 3,
				'qtd_recebida' => 3,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #27
				'id_transferencia' => 54,
				'id_produto' => 85495,
				'qtd_pedida' => 1,
				'qtd_transferida' => 1,
				'qtd_recebida' => 1,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #28
				'id_transferencia' => 55,
				'id_produto' => 79577,
				'qtd_pedida' => 1,
				'qtd_transferida' => 0,
				'qtd_recebida' => 0,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #29
				'id_transferencia' => 55,
				'id_produto' => 79582,
				'qtd_pedida' => 1,
				'qtd_transferida' => 1,
				'qtd_recebida' => 1,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #30
				'id_transferencia' => 55,
				'id_produto' => 85495,
				'qtd_pedida' => 1,
				'qtd_transferida' => 1,
				'qtd_recebida' => 1,
				'id_deposito_entrada' => 58,
				'id_deposito_saida' => 59,
			),
			array( // row #31
				'id_transferencia' => 57,
				'id_produto' => 85194,
				'qtd_pedida' => 250,
				'qtd_transferida' => 250,
				'qtd_recebida' => 250,
				'id_deposito_entrada' => 63,
				'id_deposito_saida' => 14,
			),
	);
	$count = 1 ;
	foreach ($tbl_item_transferencia_estoque as $key => $value) {
		$id_transferencia = $value['id_transferencia'];
		$id_produto = $value['id_produto'];

		echo "UPDATE tbl_item_transferencia_estoque SET id = $count WHERE id_transferencia = $id_transferencia AND id_produto = $id_produto <br/>";
		$count ++ ;

	}

?>